version: '3'

services:
  website:
    image: node:24-alpine
    container_name: web-server-tymscarcom
    command: node /site/server.mjs
    environment:
      - PORT=80
    volumes:
      - /mnt/nas/tymscar-website/site:/site:ro
    networks:
      - proxy
    restart: unless-stopped

  tunnel:
    container_name: cloudflare-tunnel-for-tymscarcom
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
        - proxy

networks:
  proxy:
    external: true
